### ISSUE TITLE
no module named 'smbus'

### ISSUE THREAD

**Issue by ar0berts** [pimoroni/bmp280-python#10]
Hi,

I have downloaded bmp280.py and placed it on the pico via Thonny - no problem. Also on the pico is v1.18(2022-01-17).uf2 from [here](https://micropython.org/download/rp2-pico/)

When I run the test examples I get stuck on 
`try:
    from smbus2 import SMBus
except ImportError:
    from smbus import SMBus`
    
with `ImportError: no module named 'smbus' `

I have tried to install the module using Thonny and have a /lib/smbus.cpython-38-x86_64-linux-gnu.so file on the pico which is almost certainly **_not_** what I want.

Any ideas as to where I have messed up as I seem unable to find an smbus.py file for micropython.?

Andrew

thonny: Thonny version: 3.3.14
Python :: 3.7']

**Comment by ar0berts** [comment]
and... even when install [smbus2](https://github.com/kplindegaard/smbus2) and put the smbus2.py file in the pico I get `ImportError: can't import name SMBus`. I'm not sure whether there is a circular dependency and am working through the smbus2.py file to try to fix it but it's probably something else!
Still stuck :-(

Andrew
[smbus2.py.txt](https://github.com/pimoroni/bmp280-python/files/7966493/smbus2.py.txt)

**Comment by Gadgetoid** [comment]
All of our Python libraries were written exclusively for the Raspberry Pi SBCs under Linux/Raspbian, and are not intended to run on the Pico. MicroPython and "real" Python are quite a world apart.

We ship our own version of MicroPython with driver for various sensors baked in- see: https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.18.0

**Comment by ar0berts** [comment]
Thanks,

I have installed v1.18.0 from the Pimoroni git page now the link is fixed and running the example [temperature-and-pressure.py](https://github.com/pimoroni/bmp280-python/blob/master/examples/temperature-and-pressure.py) script for the bmp280 gives:
```
MicroPython v1.18 on 2022-01-27; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
ImportError: no module named 'smbus'
>>> 

```
I'm baffled, having an smbus2.py script in the pico it's not used by 
`try:
    from smbus2 import SMBus
except ImportError:
    from smbus import SMBus
`
If I alter temperature-and-pressure.py to just call `from smbus2 import SMBus` I get 
```
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "smbus2.py", line 25, in <module>
  File "fcntl.py", line 1, in <module>
  File "ffi.py", line 5, in <module>
ImportError: no module named 'threading'
>>> 
```
Again,a dead end with a missing module as `sudo pip3 install threading` doesn't produce anything. 
I'm on python 3.8.5 on ubuntu 20.04 LTS.

Any pointers to where to go next gratefully received

Andrew

**Comment by Gadgetoid** [comment]
None of the code or examples in this repository will work- you need: https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/breakout_bmp280/demo_bmp280.py

All the Pico MicroPython examples live here - https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples

I… uh… have no clue where that “Hello” is coming from!

**Comment by ar0berts** [comment]
Thanks  (and Hello!),
That code works perfectly. - Please close
Andrew
