### ISSUE TITLE
Pressure is 3hPa off

### ISSUE THREAD

**Issue by ri0t** [pimoroni/bmp280-python#8]
I've checked with two trusted local barometers and https://earth.nullschool.net - my unit seems to be off, it measures 1004.92hPa, whereas it should be at 1007.

Do you have any idea on what might be causing this? Unit faulty? Calibration wrong?

It is on a Joy-IT Explorer700 where everything else works fine, if that helps. Tested to see  - by touching it for a temperature increase - if i read out the correct device.

Thanks in advance!

**Comment by Gadgetoid** [comment]
You're expecting too much from an uncalibrated sensor. It has an absolute accuracy of +- 1hPa and the accuracy of the local barometers is - presumably - an unknown quantity. A difference of 3hPa would be well within acceptable ranges.

**Comment by ri0t** [comment]
Hm, well, i've seen a constant offset of 3hPa now over a range of 1003-1009 hPa.. Seems accurate enough with that substracted, i think i'll whip up a quick script to keep tabs on that.
A non-constant error of up to 3hPa would be unacceptable, though. That would be quite like judging pressure from optical weather observation. But with a constant offset, i can live :-)

Thanks for your input!
